# buildspec.yml for bookshelf-api (Node.js Back-End for Beanstalk)
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies to ensure package-lock is up to date...
      - npm install
  build:
    commands:
      - echo Build phase complete. No manual zipping needed.
artifacts:
  files:
    - server.js
    - package.json
    - package-lock.json
  discard-paths: yes